# Generated by Django 5.1.3 on 2024-11-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='health_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
