# Generated by Django 5.1.1 on 2024-12-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario que creó el registro del equipo",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                help_text="Equipo al que pertenece el jugador",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="players",
                to="teams.team",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="player",
            unique_together={("team", "jersey_number")},
        ),
    ]
