# Generated by Django 5.1.1 on 2024-12-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tournament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre del torneo", max_length=100),
                ),
                (
                    "start_date",
                    models.DateField(help_text="Fecha de inicio del torneo"),
                ),
                (
                    "end_date",
                    models.DateField(help_text="Fecha de finalización del torneo"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ubicación donde se realiza el torneo",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del torneo",
                        null=True,
                    ),
                ),
                (
                    "teams",
                    models.ManyToManyField(
                        help_text="Equipos participantes en el torneo",
                        related_name="tournaments",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "verbose_name": "Torneo",
                "verbose_name_plural": "Torneos",
                "ordering": ["-start_date", "name"],
            },
        ),
    ]
