# Generated by Django 5.1.1 on 2024-12-10 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("matches", "0001_initial"),
        ("teams", "0001_initial"),
        ("tournaments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="team_a",
            field=models.ForeignKey(
                help_text="Primer equipo del partido",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_a",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="team_b",
            field=models.ForeignKey(
                help_text="Segundo equipo del partido",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches_as_team_b",
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="match",
            name="tournament",
            field=models.ForeignKey(
                help_text="Torneo al que pertenece el partido",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="tournaments.tournament",
            ),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="player",
            field=models.ForeignKey(
                help_text="Jugador al que pertenece este registro",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="teams.player",
            ),
        ),
        migrations.AddField(
            model_name="set",
            name="match",
            field=models.ForeignKey(
                help_text="Partido al que pertenece este set",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sets",
                to="matches.match",
            ),
        ),
        migrations.AddField(
            model_name="playerperformance",
            name="set",
            field=models.ForeignKey(
                help_text="Set en el que se registra el rendimiento",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="performances",
                to="matches.set",
            ),
        ),
    ]
